name: Deploy Fairy Forest

# Скрипт будет запускаться при каждом пуше в ветку main (или master)
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Переходим в папку с проектом
            cd /root/parallax-scrolling-website
            
            # Подтягиваем свежий код из GitHub
            git pull origin main
            
            # Компилируем новый бинарник Go
            /usr/local/go/bin/go build -o cmd/server/mywebsite cmd/server/main.go || go build -o cmd/server/mywebsite cmd/server/main.go

            
            # Перезапускаем системную службу
            systemctl restart mysite.service